### ISSUE TITLE
Plan for WorkGraph

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-workgraph#180]
1. Can some of the features be released first? For example, without PythonJob
**TODO** give a list of features,
 - want to released
 - released as experimental features
 - not released

## Timeline
- 2024-08, pre-release, and ask people to try, Coding week.
- 2024-11, Stable release
- 2025 early, virtual tutorial

### Core feature to be included in the stable release (v1.0)
- [ ] WorkGraph and WorkGraphEngine
- [ ] Graph Builder
- [ ] [While WorkGraph](https://aiida-workgraph.readthedocs.io/en/latest/howto/while.html)
- [ ] [Calling WorkGraph within a WorkChain](http://aiida-workgraph/howto/workchain_call_workgraph.html): There may arise scenarios where integrating a WorkGraph workflow within a WorkChain.
- [ ] [ShellJob task](https://aiida-workgraph.readthedocs.io/en/latest/built-in/shelljob.html)
- [ ] [Error handler](https://aiida-workgraph.readthedocs.io/en/latest/howto/error_resistant.html)
- [ ] [Modify and restart a WorkGraph](https://aiida-workgraph.readthedocs.io/en/latest/howto/restart.html)
- [ ] [Continue a finished WorkGraph](https://aiida-workgraph.readthedocs.io/en/latest/howto/continue_finished_workgraph.html)
- [ ] Widget
- [ ] Web App

### Version 1.1

- [ ] [PythonJob](https://aiida-workgraph.readthedocs.io/en/latest/built-in/pythonjob.html): An important feature requiring attention. Consider spending a day to enhance aspects such as:
  - [ ] [Data serializers](https://aiida-workgraph.readthedocs.io/en/latest/built-in/pythonjob.html#Define-your-data-serializer): Discuss the feasibility of a common data serializer repository.
  - [ ] [Namespace output improvements](https://aiida-workgraph.readthedocs.io/en/latest/built-in/pythonjob.html#Namespace-Output)
  - [ ] Improve virtual environments on remote computers.
  - [x] Simplify the usage of `PythonJob` outside WorkGraph, e.g., inside a WorkChain.
  - [ ] Compare with [aiida-dynamic-workflows](https://github.com/microsoft/aiida-dynamic-workflows/tree/main). If possible, evaluate both aiida-dynamic-workflows and PythonJob to understand their strengths and limitations. 
  - [ ] Data handling with Pickle.

- [ ] **Protocol** and **get_builder_from_protocol** is commonly used in WorkChain. Can we implement similar concept for WorkGraph? Here is a simple [protocol](https://aiida-workgraph.readthedocs.io/en/latest/howto/protocol.html), but would be great we implment a better one.

**Comment by superstar54** [comment]
This issue is outdated.
